### ISSUE TITLE
Header - I collegamenti alle pagine non funzionano

### ISSUE THREAD

**Issue by alessandrocardelli** [cristiano-c1/themekit#14]
![schermata 2018-04-11 alle 09 14 08](https://user-images.githubusercontent.com/38191355/38601679-bdba9760-3d68-11e8-9bac-84ea0dd1a959.png)
Funziona solo SPEDIZIONI.

**1. ASSISTENZA** - Nel vecchio sito si apriva una pagina con un form da compilare per richiedere assistenza.
La pagina sarebbe questa /pages/richiedi-una-consulenza, la trovi in Online Store -> Pages
**2. SICUREZZA** - La pagina è /pages/pagamenti
**3. RESO GRATUITO** - La pagina è /pages/recesso

**Comment by alessandrocardelli** [comment]
Ho aggiunto al main menu il bottone RICHIEDI UNA CONSULENZA che però rimanda alla pagina col form che non funziona (vedi sopra)

**Comment by alessandrocardelli** [comment]
4. La cosa del doppio titolo l'aggiusto io, è in tutte la pagine importate

**Comment by cristiano-c1** [comment]
le pagine me le devi creare tu.
non vedo link da nessuna parte qua

**Comment by alessandrocardelli** [comment]
le pagine ci sono già, tranne quella richiedi assistenza che ha bisogno di un form come ti dicevo sopra
I link sono quelli che ti ho scritto sopra
ASSISTENZA /pages/richiedi-una-consulenza
SICUREZZA /pages/pagamenti
RESO GRATUITO /pages/recesso

**Comment by cristiano-c1** [comment]
si visti ora scusa

**Comment by alessandrocardelli** [comment]
il form da compilare nel vecchio sito inviava poi una mail a supporto@ilquadrifoglioerboristeria.it
https://ilquadrifoglioerboristeria.it/contacts/

**Comment by cristiano-c1** [comment]
@alessandrocardelli ??? non puoi creare form di contatto?

**Comment by alessandrocardelli** [comment]
Si, l'ho creata
https://il-quadrifoglio.myshopify.com/admin/themes/13687488571/editor#/pages/richiedi-una-consulenza

La pagina a cui devi collegare l'icona è /pages/richiedi-una-consulenza

**Comment by cristiano-c1** [comment]
@alessandrocardelli vista, onestamente lascerei solo il form e farei una pagina contatti separata. uno quando vuol richiedere una consulenza non gliene frega nulla della google maps e similia..... no?
