### ISSUE TITLE
Pagina collezione: Sidebar - elementi mancanti

### ISSUE THREAD

**Issue by cristiano-c1** [cristiano-c1/themekit#2]
Completa e quando fatto dimmi pure

**Comment by alessandrocardelli** [comment]
Intendi quel menu Categorie?
Quelle nel menu li a sinistra non sono vere e proprie categorie ma le tags, infatti ti fa vedere anche robe tipo IVA10 ecc...
Andrebbe disattivata quella roba li e al suo posto ci metterei il sidebar menu come hai fatto in home.

**Comment by alessandrocardelli** [comment]
non capisco, la sidebar della pagina collezione va sostituita col menu sintomi perché devo aggiungerci della roba? 
e comunque a livello di tags per il momento ci sono tutte (importate in automatico con il tool di migrazione)?

**Comment by cristiano-c1** [comment]
Perche' abbiamo un tema con mille feature interessanti che non sono presenti sul sito attuale e dal momento che lo stiamo rifacendo vale la pena valutare integrazioni /cambiamenti, detto questo il contenuto di quella sidebar dovrebbe essere gestibile via admin (lavoro tuo).

In caso contrario fammelo presente che lo scrivo io.

Quello che volevo e' che : 
1. controllassi gli elementi disponibili nel tema (https://beauty-store-11.myshopify.com/)
2. mi popoli la sidebar con gli elementi disponibili da admin

anche in homepage ad esempio c'e' un fracco di roba banner eccetera eccetera che si potrebbe pensare come usare.

non dobbiamo per forza copiare il sito di ora paro paro, anzi......

**Comment by alessandrocardelli** [comment]
Ok avevo capito male, pensavo che quando dicevi "aggiungi gli elementi" ti riferissi alle tags nell'elenco categorie.
Adesso ho capito, ci guardo.

**Comment by alessandrocardelli** [comment]
Per la [pagina collezione](https://beauty-store-11.myshopify.com/collections/all) io vedo:
Elenco CATEGORIES - Non ci serve e lo già disattivato
Filters - Si, ci servono
Custom CMS widget - Direi di tenerlo disabilitato per il momento, non saprei cosa metterci
