### ISSUE TITLE
Pagina checkout e account personale - Aggiungere un campo per l'inserimento CF

### ISSUE THREAD

**Issue by alessandrocardelli** [cristiano-c1/themekit#20]
Ho creato un metafield "c_f.codice_fiscale" per inserire appunto il CF.
Bisogna aggiungerlo come campo modificabile sia nella pagina di checkout (quando si inseriscono i dati di spedizione), sia nella pagina dell'account personale.

**Comment by alessandrocardelli** [comment]
[https://www.castoro.me/partita-iva-codice-fiscale-shopify-gestirle/](url)

**Comment by cristiano-c1** [comment]
@alessandrocardelli il link qui sopra non va

**Comment by cristiano-c1** [comment]
@alessandrocardelli fatto, soluzione sporca
