### ISSUE TITLE
Scheda prodotto: Contenuto tabs

### ISSUE THREAD

**Issue by cristiano-c1** [cristiano-c1/themekit#3]
Credo sia da rivedere

**Comment by alessandrocardelli** [comment]
Nel sito vecchio tenevamo solo la descrizione, io farei così anche qua tanto le "regole" di spedizione e reso sono uguali per tutti i prodotti, size chart non ce ne facciamo una ceppa e recensioni secondo me per il momento possiamo anche stare senza
