### ISSUE TITLE
Footer: menu account

### ISSUE THREAD

**Issue by cristiano-c1** [cristiano-c1/themekit#4]
non ho ben capito come crearlo, guardaci se si puo fare dall admin senno passami la issue riassegnandola e lo scrivo io
![schermata 2018-04-08 alle 22 11 16](https://user-images.githubusercontent.com/325296/38472015-c403b552-3b79-11e8-98fc-295b8319a8b3.png)

**Comment by alessandrocardelli** [comment]
Allora, ho creato un menu "Account" copiando i link del dropdown in alto a destra ma ci sono alcuni problemi:
**1. Senza aver eseguito l'accesso**
Il dropdown in alto a destra mostra comunque "Lista dei desideri", non credo che si debba vedere se non hai fatto il login, giusto?

**2. Il link alla wishlist non funge**
Il link alla "Lista dei desideri" in ogni caso porta a una 404 (ho anche provato ad aggiungere qualcosa alla mia lista)

**3. Il menu nel footer è statico**
Creandolo dall'admin non credo si possano stabilire delle condizioni su cosa visualizzare.
Se possibile credo che dovrebbe essere una "copia" del dropdown in alto a destra e cioè:
**Ad accesso non eseguito** - Accedi, Crea un account
**Ad accesso eseguito** - Il mio account (con url /account), Lista dei desideri, Esci

**Comment by cristiano-c1** [comment]
1. va bene cosi, quando ci clicchi ti chiede di loggare.
2. Crea issue (con descrizioni del caso)
3. Crea issue e assegna
