### ISSUE TITLE
Footer : loghi pagamento

### ISSUE THREAD

**Issue by cristiano-c1** [cristiano-c1/themekit#5]
dovresti cercare nell internet i loghi dei nostri pagamenti in formato vettoriale (.svg tipo) o .png
puoi incollare quei nella issue quello che trovi che poi lo vedo io

**Comment by alessandrocardelli** [comment]
[Archivio.zip](https://github.com/cristiano-c1/themekit/files/1889234/Archivio.zip)
A [questa pagina](https://stripe.com/about/resources) ci sono le info per i loghi nel kit Stripe (dentro lo zip)
