### ISSUE TITLE
Il menu Account nel footer è statico

### ISSUE THREAD

**Issue by alessandrocardelli** [cristiano-c1/themekit#8]
Creandolo dall'admin non credo si possano stabilire delle condizioni su cosa visualizzare.
Se possibile credo che dovrebbe essere una "copia" del dropdown in alto a sinistra e cioè:
Ad accesso non eseguito - Accedi, Crea un account
Ad accesso eseguito - Il mio account (con url /account), Lista dei desideri, Esci

**Comment by cristiano-c1** [comment]
@alessandrocardelli anche nel sito live e' cosi e farlo come vuoi tu e' troppo sbatti, chiudo issue.
